[package]
name = "kwallet"
version = "0.1.0"
edition = "2024"
description = "Simple Kaspa wallet"
authors = ["Hung Tran"]

[dependencies]
clap = { version = "4.4", features = ["derive"] }
kaspa-bip32 = "2.1.0"
kaspa-wrpc-client = "2.1.0"
tokio = { version = "1.53.2", features = ["macros", "rt-multi-thread"] }
kaspa-addresses = "2.1.0"
