[package]
name = "kwallet"
version = "0.1.0"
edition = "2024"
description = "Simple Kaspa wallet"
authors = ["Hung Tran"]

[dependencies]
clap = { version = "4.4", features = ["derive"] }
kaspa-wrpc-client = { git = "https://github.com/kaspanet/rusty-kaspa", tag = "v2.1.0", version = "2.1.0" }
tokio = { version = "1.53.2", features = ["macros", "rt-multi-thread"] }
